config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  root 'widgets#index'
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  def index
    @widgets = Widget.all
  end

  def new
    @widget = Widget.new
  end

  def create
    @widget = Widget.new(widget_params)
    @widget.save
    redirect_to root_path
  end

  def edit
    @widget = Widget.find(params[:id])
  end

  def update
    @widget = Widget.find(params[:id])
    if @widget.update(widget_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @widget = Widget.find(params[:id])
  end

  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy
    redirect_to widgets_path
  end

  private

  def widget_params
    params.require(:widget).permit(:name, :description, :age, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Widgets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/widgets/edit.html.erb
<h1>Edit Widget</h1>
<%= form_for @widget do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.submit %>
<% end %>

app/views/widgets/index.html.erb
<h1>Widgets</h1>
<%= link_to "New Widget", new_widget_path %>

<% @widgets.each do |widget| %>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Age</th>
  </tr>
  <tr>
    <td><%= widget.name %></td>
    <td><%= widget.description %></td>
    <td><%= widget.age %></td>
    <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
    <td><%= link_to 'Show', widget_path(widget) %></td>
    <td><%= link_to 'Delete', widget_path(widget), method: :delete %></td>
  </tr>
</table>
<% end %>

app/views/widgets/index.html.haml
.container
  %h1 Widgets
  - @widgets.each do |widget|
    .box.panel.panel-default.col-lg-3
      .panel-body.text-center
        .col-md-3
          = image_tag widget.image
          = link_to widget.name, widget_path(widget)
  = link_to "New Widget", new_widget_path, class: 'btn btn-primary'

app/views/widgets/new.html.erb
<h1>Widget Factory</h1>
<%= form_for @widget do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :age %>
  <%= f.text_field :age %>
  
  <%= f.submit %>
<% end %>

app/views/widgets/new.html.haml
%h1 Widget Factory
= form_for @widget do |f|
  = f.label :name
  = f.text_field :name

  = f.label :description
  = f.text_field :description

  = f.label :age
  = f.text_field :age

  = f.label :image
  = f.file_field :image
  = f.hidden_field :image_cache

  = f.submit

app/views/widgets/show.html.erb
<h1><%= @widget.name %></h1>
<%= @widget.description %></br>
<%= @widget.age %></br>
<%= link_to 'All Widgets', widgets_path %> |
<%= link_to 'Edit', edit_widget_path(@widget) %>

app/views/widgets/show.html.haml
%h1= @widget.name
= @widget.description
= @widget.age
= @widget.image
%br
= link_to 'All Widgets', widgets_path
|
= link_to 'Edit', edit_widget_path(@widget)
|
= link_to 'Delete', widget_path(@widget), method: :delete